# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e307d9e39b1f52479b217aead1a4bc5d"
name = "sustainability-test-app"
handle = "sustainability-test-app"
application_url = "https://visual-investigations-eugene-pts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mona-watches-demo.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://visual-investigations-eugene-pts.trycloudflare.com/auth/callback",
  "https://visual-investigations-eugene-pts.trycloudflare.com/auth/shopify/callback",
  "https://visual-investigations-eugene-pts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
